from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.index, name='admin_index'),
    url(r'^login/$', views.login, name='admin_login'),
    url(r'^logout/$', views.logout, name='admin_logout'),
    url(r'^user/$', views.user, name='admin_user'),
    # url(r'^country/$', views.country, name='admin_country'),
    # url(r'^category/$', views.category, name='admin_category'),
    url(r'^project/$', views.project, name='admin_project'),
    url(r'^client/$', views.client, name='admin_client'),
    # url(r'^photo/$', views.photo, name='admin_photo'),
    # url(r'^video/$', views.video, name='admin_video'),
    # url(r'^instagram/$', views.instagram, name='admin_instagram'),
    url(r'^list_user/$', views.list_user, name='list_user'),
    url(r'^create_user/$', views.create_user, name='create_user'),
    url(r'^update_user/$', views.update_user, name='update_user'),
    url(r'^get_user/$', views.get_user, name='get_user'),
    url(r'^list_country/$', views.list_country, name='list_country'),
    url(r'^create_country/$', views.create_country, name='create_country'),
    url(r'^update_country/$', views.update_country, name='update_country'),
    url(r'^get_country/$', views.get_country, name='get_country'),
    url(r'^list_category/$', views.list_category, name='list_category'),
    url(r'^create_category/$', views.create_category, name='create_category'),
    url(r'^update_category/$', views.update_category, name='update_category'),
    url(r'^get_category/$', views.get_category, name='get_category'),
    url(r'^list_segment/$', views.list_segment, name='list_segment'),
    url(r'^create_segment/$', views.create_segment, name='create_segment'),
    url(r'^update_segment/$', views.update_segment, name='update_segment'),
    url(r'^get_segment/$', views.get_segment, name='get_segment'),
    url(r'^list_company/$', views.list_company, name='list_company'),
    url(r'^create_company/$', views.create_company, name='create_company'),
    url(r'^update_company/$', views.update_company, name='update_company'),
    url(r'^get_company/$', views.get_company, name='get_company'),
    url(r'^list_client/$', views.list_client, name='list_client'),
    url(r'^create_client_id/$', views.create_client_id, name='create_client_id'),
    url(r'^create_client/$', views.create_client, name='create_client'),
    url(r'^update_client/$', views.update_client, name='update_client'),
    url(r'^get_client/$', views.get_client, name='get_client'),
    url(r'^delete_client/$', views.delete_client, name='delete_client'),
    url(r'^list_project/$', views.list_project, name='list_project'),
    url(r'^create_project_id/$', views.create_project_id, name='create_project_id'),
    url(r'^create_project/$', views.create_project, name='create_project'),
    url(r'^update_project/$', views.update_project, name='update_project'),
    url(r'^get_project/$', views.get_project, name='get_project'),
    url(r'^delete_project/$', views.delete_project, name='delete_project'),
    url(r'^list_photo/$', views.list_photo, name='list_photo'),
    url(r'^create_photo/$', views.create_photo, name='create_photo'),
    url(r'^regist_photo/$', views.regist_photo, name='regist_photo'),
    url(r'^delete_photo/$', views.delete_photo, name='delete_photo'),
    url(r'^update_photo/$', views.update_photo, name='update_photo'),
    url(r'^get_photo/$', views.get_photo, name='get_photo'),
    url(r'^list_video/$', views.list_video, name='list_video'),
    url(r'^create_video/$', views.create_video, name='create_video'),
    url(r'^regist_video/$', views.regist_video, name='regist_video'),
    url(r'^delete_video/$', views.delete_video, name='delete_video'),
    url(r'^update_video/$', views.update_video, name='update_video'),
    url(r'^get_video/$', views.get_video, name='get_video'),
    # url(r'^list_instagram/$', views.list_instagram, name='list_instagram'),
    # url(r'^create_instagram/$', views.create_instagram, name='create_instagram'),
    # url(r'^update_instagram/$', views.update_instagram, name='update_instagram'),
    # url(r'^get_instagram/$', views.get_instagram, name='get_instagram'),
]