# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_nickname', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_client',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_country',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(default=0)),
                ('url', models.CharField(max_length=255)),
                ('thumb', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('hash_tag', models.CharField(max_length=255)),
                ('regist_date', models.DateField()),
                ('status', models.SmallIntegerField(default=0)),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_media',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('country', models.ForeignKey(db_column=b'country', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Country')),
                ('user', models.OneToOneField(db_column=b'user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('outline', models.TextField()),
                ('result', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('note', models.CharField(max_length=255)),
                ('category', models.ForeignKey(db_column=b'category', on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
                ('client', models.ForeignKey(db_column=b'client', on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
            options={
                'db_table': 't_project',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_segment',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='project',
            field=models.ForeignKey(db_column=b'project', on_delete=django.db.models.deletion.CASCADE, to='backend.Project'),
        ),
        migrations.AddField(
            model_name='media',
            name='register',
            field=models.ForeignKey(db_column=b'register', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(db_column=b'country', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Country'),
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.ForeignKey(db_column=b'segment', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Segment'),
        ),
    ]
